mariadb:
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: gp3
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
  auth:
    rootPassword: rootpassword
    database: bitnami_wordpress
    username: bn_wordpress
    password: bn_wordpress

persistence:
  enabled: true
  size: 8Gi
  storageClass: gp3

wordpressUsername: admin
wordpressPassword: admin123

service:
  type: LoadBalancer

image:
  registry: docker.io
  repository: bitnamilegacy/wordpress

global:
  security:
    allowInsecureImages: true
