mariadb:
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: gp3
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
  auth:
    existingSecret: wordpress

persistence:
  enabled: true
  size: 8Gi
  storageClass: gp3

wordpressExistingSecret: wordpress
existingSecret: wordpress

service:
  type: LoadBalancer

image:
  registry: docker.io
  repository: bitnamilegacy/wordpress

global:
  security:
    allowInsecureImages: true
